//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class apiUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public apiUser()
        {
            this.apiUserRequests = new HashSet<apiUserRequest>();
        }
    
        public int apiUserCode { get; set; }
        public string apiUserName { get; set; }
        public string apiUserKey { get; set; }
        public string apiUserValue { get; set; }
        public System.DateTime dateFrom { get; set; }
        public Nullable<System.DateTime> dateTo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<apiUserRequest> apiUserRequests { get; set; }
    }
}
