//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class apiUserRequest
    {
        public int apiUserRequestCode { get; set; }
        public Nullable<int> apiUserCode { get; set; }
        public string apiUserKey { get; set; }
        public string apiUserValue { get; set; }
        public string apiUserRequestURL { get; set; }
        public string apiUserRequestIP { get; set; }
        public System.DateTime apiUserRequestDate { get; set; }
    
        public virtual apiUser apiUser { get; set; }
    }
}
