//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class cardWorkerStopActive
    {
        public int cardWorkerStopActiveCode { get; set; }
        public int workerCode { get; set; }
        public Nullable<int> cardCode { get; set; }
        public string reasons { get; set; }
        public Nullable<System.DateTime> dateStartStopActive { get; set; }
        public Nullable<System.DateTime> dateEndStopActive { get; set; }
        public string notes { get; set; }
        public Nullable<int> userInsertCode { get; set; }
        public Nullable<System.DateTime> dateInsert { get; set; }
        public string ipInsert { get; set; }
        public Nullable<int> userUpdateCode { get; set; }
        public Nullable<System.DateTime> dateUpdate { get; set; }
        public string ipUpdate { get; set; }
    
        public virtual card card { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual worker worker { get; set; }
    }
}
