//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class companyCardRequest
    {
        public int companyCardRequestCode { get; set; }
        public int cardsRequestCode { get; set; }
        public int cardsStatusCode { get; set; }
        public Nullable<System.DateTime> dateInsert { get; set; }
    
        public virtual cardsRequest cardsRequest { get; set; }
        public virtual cardsStatu cardsStatu { get; set; }
    }
}
