//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class extractProcess
    {
        public int extractProcessCode { get; set; }
        public Nullable<int> officeInsuranceCode { get; set; }
        public string extractName { get; set; }
        public int processCode { get; set; }
        public Nullable<int> extractProcessID { get; set; }
        public Nullable<decimal> budget { get; set; }
        public Nullable<int> extractTypeCode { get; set; }
        public Nullable<int> processSubContractorCode { get; set; }
        public Nullable<int> missionExpiredTypeCode { get; set; }
        public string recieverContractor { get; set; }
        public Nullable<System.DateTime> dateExtract { get; set; }
        public Nullable<bool> isPaid { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<bool> extractAccept { get; set; }
        public Nullable<System.DateTime> dateAccept { get; set; }
        public Nullable<int> userCodeAccept { get; set; }
        public string ipAcceptExtract { get; set; }
        public Nullable<int> userInsertCode { get; set; }
        public Nullable<System.DateTime> dateInsert { get; set; }
        public string ipInsert { get; set; }
        public Nullable<int> userUpdateCode { get; set; }
        public Nullable<System.DateTime> dateUpdate { get; set; }
        public string ipUpdate { get; set; }
    
        public virtual extractType extractType { get; set; }
        public virtual officeInsurance officeInsurance { get; set; }
        public virtual processType processType { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual process process { get; set; }
    }
}
