//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class migrehab
    {
        public int migrehabCode { get; set; }
        public string AreaCode { get; set; }
        public string OfficeCode { get; set; }
        public string ContractionCode { get; set; }
        public string processYear { get; set; }
        public string processNumber { get; set; }
        public string bandCode { get; set; }
        public string ActivityType { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> startRealDate { get; set; }
        public Nullable<System.DateTime> EndRealDate { get; set; }
        public string startBudget { get; set; }
        public string endBudget { get; set; }
        public Nullable<System.DateTime> lastWorkDate { get; set; }
        public string bandNumber { get; set; }
        public string processFlag { get; set; }
        public string processShow { get; set; }
        public string ActivityTypeCode { get; set; }
        public string ActivityPrecent { get; set; }
        public string endReason { get; set; }
        public string totalEndBudget { get; set; }
        public string WorkDoneBudget { get; set; }
        public string updateFlag { get; set; }
        public string ContractorNumber { get; set; }
        public string ContractorCode { get; set; }
        public Nullable<System.DateTime> startContractorActiveDate { get; set; }
        public string referenceSideType { get; set; }
        public string referenceSideNumber { get; set; }
        public string referencesideFlag { get; set; }
        public string subContractorNumber { get; set; }
        public string subContractorNatural { get; set; }
        public string subContractorFlag { get; set; }
        public string budgetType { get; set; }
        public string budgetTotal { get; set; }
        public string extractDescription { get; set; }
        public string lastExtract { get; set; }
        public string additionalBudget { get; set; }
        public string monthlySubscribe { get; set; }
        public Nullable<System.DateTime> budgetDate { get; set; }
        public Nullable<int> govermentCode { get; set; }
        public Nullable<int> centerCode { get; set; }
        public Nullable<int> villageCode { get; set; }
        public string buildingNumber { get; set; }
        public string address { get; set; }
        public string activityNumber { get; set; }
    }
}
