//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class orascomWorker
    {
        public double م { get; set; }
        public Nullable<int> processCode { get; set; }
        public Nullable<double> الرقم_القومى { get; set; }
        public string الاسم { get; set; }
        public string المهنة { get; set; }
        public string العنوان { get; set; }
        public string رقم_الهاتف { get; set; }
        public string موقع_القياس { get; set; }
        public Nullable<System.DateTime> تاريخ_الميلاد { get; set; }
        public Nullable<double> السن { get; set; }
        public string درجة_المهارة { get; set; }
        public string الرقم_التأميني { get; set; }
        public string الحالة_التأمينية { get; set; }
        public string Rany { get; set; }
        public Nullable<double> F14 { get; set; }
        public string wsdlError { get; set; }
        public string wsdlResponse { get; set; }
        public Nullable<System.DateTime> wsdlDate { get; set; }
    }
}
