//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class permissionAreaOffice
    {
        public int permissionAreaOfficeCode { get; set; }
        public int groupAreaOfficeSettingCode { get; set; }
        public Nullable<int> officeInsuranceCode { get; set; }
        public Nullable<int> userInsertCode { get; set; }
        public Nullable<System.DateTime> dateInsert { get; set; }
        public string ipInsert { get; set; }
    
        public virtual officeInsurance officeInsurance { get; set; }
        public virtual groupAreaOfficeSetting groupAreaOfficeSetting { get; set; }
        public virtual user user { get; set; }
    }
}
