//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class processSubContractor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public processSubContractor()
        {
            this.missionSubContractors = new HashSet<missionSubContractor>();
            this.processUsers = new HashSet<processUser>();
        }
    
        public int processSubContractorCode { get; set; }
        public int processCode { get; set; }
        public Nullable<int> contractorCode { get; set; }
        public Nullable<bool> contractorType { get; set; }
        public string contractorProcessNumber { get; set; }
        public Nullable<bool> subContractorAccept { get; set; }
        public Nullable<System.DateTime> dateAccept { get; set; }
        public Nullable<int> userCodeAccept { get; set; }
        public string ipAcceptProcess { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isFreeze { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<int> userInsertCode { get; set; }
        public Nullable<System.DateTime> dateInsert { get; set; }
        public string ipInsert { get; set; }
        public Nullable<int> userUpdateCode { get; set; }
        public Nullable<System.DateTime> dateUpdate { get; set; }
        public string ipUpdate { get; set; }
        public Nullable<bool> seen { get; set; }
        public Nullable<int> seenEmployeeInsuranceUserCode { get; set; }
        public Nullable<System.DateTime> dateSeenEmployeeInsurance { get; set; }
        public Nullable<int> seenMainContractorUserCode { get; set; }
        public Nullable<System.DateTime> dateSeenMainContractor { get; set; }
        public Nullable<bool> seenEmployeeInsurance { get; set; }
        public Nullable<bool> seenMainContractor { get; set; }
    
        public virtual referenceSideContractor referenceSideContractor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<missionSubContractor> missionSubContractors { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual user user2 { get; set; }
        public virtual user user3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processUser> processUsers { get; set; }
        public virtual process process { get; set; }
    }
}
