//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class processUser
    {
        public int processUserCode { get; set; }
        public Nullable<int> processSubContractorCode { get; set; }
        public Nullable<int> userCode { get; set; }
        public Nullable<bool> contractorType { get; set; }
        public Nullable<int> smsReturnCode { get; set; }
        public Nullable<System.DateTime> smsReturnDate { get; set; }
        public Nullable<int> userInsertCode { get; set; }
        public Nullable<System.DateTime> dateInsert { get; set; }
        public string ipInsert { get; set; }
        public Nullable<bool> seen { get; set; }
    
        public virtual processSubContractor processSubContractor { get; set; }
        public virtual smsReturn smsReturn { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
