//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class processStop
    {
        public int processStopCode { get; set; }
        public int processCode { get; set; }
        public int stopStatusCode { get; set; }
        public Nullable<System.DateTime> dateStartProcessStop { get; set; }
        public Nullable<System.DateTime> dateEndProcessStop { get; set; }
        public string processStopReason { get; set; }
        public Nullable<int> userInsertCode { get; set; }
        public Nullable<System.DateTime> dateInsert { get; set; }
        public string ipInsert { get; set; }
        public Nullable<int> userUpdateCode { get; set; }
        public Nullable<System.DateTime> dateUpdate { get; set; }
        public string ipUpdate { get; set; }
    
        public virtual stopStatu stopStatu { get; set; }
        public virtual user user { get; set; }
        public virtual process process { get; set; }
    }
}
