//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class referenceSideContractor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public referenceSideContractor()
        {
            this.processSubContractors = new HashSet<processSubContractor>();
            this.users = new HashSet<user>();
            this.users1 = new HashSet<user>();
            this.processes = new HashSet<process>();
        }
    
        public int referenceSideContractorCode { get; set; }
        public string referenceSideContractorName { get; set; }
        public Nullable<int> legalEntityCode { get; set; }
        public string referenceSideContractorInsuranceNum { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string ownerNumber { get; set; }
        public string ownerName { get; set; }
        public Nullable<int> ownerlegalEntityCode { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string e_mail { get; set; }
        public Nullable<int> userInsertCode { get; set; }
        public Nullable<System.DateTime> dateInsert { get; set; }
        public string ipInsert { get; set; }
        public Nullable<int> userUpdateCode { get; set; }
        public Nullable<System.DateTime> dateUpdate { get; set; }
        public string ipUpdate { get; set; }
    
        public virtual legalEntity legalEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processSubContractor> processSubContractors { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<process> processes { get; set; }
    }
}
