//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    
    public partial class spGetAllContractorsAndRefSide_Result1
    {
        public Nullable<int> referenceSideContractorCode { get; set; }
        public string referenceSideContractorName { get; set; }
    }
}
