//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.attachmentTypes = new HashSet<attachmentType>();
            this.attachmentTypes1 = new HashSet<attachmentType>();
            this.cardsRequests = new HashSet<cardsRequest>();
            this.cardsRequests1 = new HashSet<cardsRequest>();
            this.cardsRequests2 = new HashSet<cardsRequest>();
            this.cardsRequests3 = new HashSet<cardsRequest>();
            this.referenceSideContractors = new HashSet<referenceSideContractor>();
            this.referenceSideContractors1 = new HashSet<referenceSideContractor>();
            this.manPowers = new HashSet<manPower>();
            this.manPowers1 = new HashSet<manPower>();
            this.medicalInsurances = new HashSet<medicalInsurance>();
            this.medicalInsurances1 = new HashSet<medicalInsurance>();
            this.extractProcesses = new HashSet<extractProcess>();
            this.extractProcesses1 = new HashSet<extractProcess>();
            this.processNotes = new HashSet<processNote>();
            this.processOppositions = new HashSet<processOpposition>();
            this.processOppositions1 = new HashSet<processOpposition>();
            this.processOppositions2 = new HashSet<processOpposition>();
            this.processSites = new HashSet<processSite>();
            this.processSites1 = new HashSet<processSite>();
            this.processStops = new HashSet<processStop>();
            this.processSubContractors = new HashSet<processSubContractor>();
            this.processSubContractors1 = new HashSet<processSubContractor>();
            this.processSubContractors2 = new HashSet<processSubContractor>();
            this.processSubContractors3 = new HashSet<processSubContractor>();
            this.processUserLettersSites = new HashSet<processUserLettersSite>();
            this.processUserLettersSites1 = new HashSet<processUserLettersSite>();
            this.processUsers = new HashSet<processUser>();
            this.processUsers1 = new HashSet<processUser>();
            this.groups = new HashSet<group>();
            this.groups1 = new HashSet<group>();
            this.groupPermissions = new HashSet<groupPermission>();
            this.groupPermissions1 = new HashSet<groupPermission>();
            this.groupUsers = new HashSet<groupUser>();
            this.groupUsers1 = new HashSet<groupUser>();
            this.groupUsers2 = new HashSet<groupUser>();
            this.permissionAreaOffices = new HashSet<permissionAreaOffice>();
            this.cardWorkerStopActives = new HashSet<cardWorkerStopActive>();
            this.cardWorkerStopActives1 = new HashSet<cardWorkerStopActive>();
            this.workerContacts = new HashSet<workerContact>();
            this.workerDetails = new HashSet<workerDetail>();
            this.workerDetails1 = new HashSet<workerDetail>();
            this.workerInjuries = new HashSet<workerInjury>();
            this.workerInjuries1 = new HashSet<workerInjury>();
            this.workerOfficeInsurances = new HashSet<workerOfficeInsurance>();
            this.workerOfficeInsurances1 = new HashSet<workerOfficeInsurance>();
            this.workerPeriods = new HashSet<workerPeriod>();
            this.workerPeriods1 = new HashSet<workerPeriod>();
            this.workers = new HashSet<worker>();
            this.workers1 = new HashSet<worker>();
            this.workerAttendances = new HashSet<workerAttendance>();
            this.workerAttendances1 = new HashSet<workerAttendance>();
            this.processes = new HashSet<process>();
            this.processes1 = new HashSet<process>();
            this.processes2 = new HashSet<process>();
        }
    
        public int userCode { get; set; }
        public string userFullName { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string nationalID { get; set; }
        public Nullable<int> officeInsuranceCode { get; set; }
        public Nullable<int> referenceSideCode { get; set; }
        public Nullable<int> contractorCode { get; set; }
        public bool isActive { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public string imageURL { get; set; }
        public string address { get; set; }
        public string e_mail { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public Nullable<bool> changePassword { get; set; }
        public Nullable<System.DateTime> dateChangePassword { get; set; }
        public Nullable<int> smsReturnCode { get; set; }
        public Nullable<System.DateTime> smsReturnDate { get; set; }
        public Nullable<int> userInsertCode { get; set; }
        public Nullable<System.DateTime> dateInsert { get; set; }
        public string ipInsert { get; set; }
        public Nullable<int> userUpdateCode { get; set; }
        public Nullable<System.DateTime> dateUpdate { get; set; }
        public string ipUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attachmentType> attachmentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attachmentType> attachmentTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cardsRequest> cardsRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cardsRequest> cardsRequests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cardsRequest> cardsRequests2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cardsRequest> cardsRequests3 { get; set; }
        public virtual officeInsurance officeInsurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<referenceSideContractor> referenceSideContractors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<referenceSideContractor> referenceSideContractors1 { get; set; }
        public virtual referenceSideContractor referenceSideContractor { get; set; }
        public virtual referenceSideContractor referenceSideContractor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<manPower> manPowers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<manPower> manPowers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medicalInsurance> medicalInsurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medicalInsurance> medicalInsurances1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<extractProcess> extractProcesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<extractProcess> extractProcesses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processNote> processNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processOpposition> processOppositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processOpposition> processOppositions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processOpposition> processOppositions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processSite> processSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processSite> processSites1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processStop> processStops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processSubContractor> processSubContractors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processSubContractor> processSubContractors1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processSubContractor> processSubContractors2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processSubContractor> processSubContractors3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processUserLettersSite> processUserLettersSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processUserLettersSite> processUserLettersSites1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processUser> processUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processUser> processUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<group> groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<group> groups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<groupPermission> groupPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<groupPermission> groupPermissions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<groupUser> groupUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<groupUser> groupUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<groupUser> groupUsers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<permissionAreaOffice> permissionAreaOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cardWorkerStopActive> cardWorkerStopActives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cardWorkerStopActive> cardWorkerStopActives1 { get; set; }
        public virtual smsReturn smsReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workerContact> workerContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workerDetail> workerDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workerDetail> workerDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workerInjury> workerInjuries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workerInjury> workerInjuries1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workerOfficeInsurance> workerOfficeInsurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workerOfficeInsurance> workerOfficeInsurances1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workerPeriod> workerPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workerPeriod> workerPeriods1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<worker> workers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<worker> workers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workerAttendance> workerAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workerAttendance> workerAttendances1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<process> processes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<process> processes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<process> processes2 { get; set; }
    }
}
