//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class workerAttendance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public workerAttendance()
        {
            this.workerAttendanceInsurances = new HashSet<workerAttendanceInsurance>();
        }
    
        public int workerAttendanceCode { get; set; }
        public int workerCode { get; set; }
        public int processCode { get; set; }
        public Nullable<int> skillDegreeCode { get; set; }
        public Nullable<int> cardCode { get; set; }
        public Nullable<byte> typeAttendence { get; set; }
        public Nullable<System.DateTime> dateAttendence { get; set; }
        public Nullable<int> statusFirstAttendMonthWSDLCode { get; set; }
        public Nullable<System.DateTime> statusFirstAttendMonthWSDLDate { get; set; }
        public Nullable<int> attendanceSheetCode { get; set; }
        public Nullable<bool> testProduction { get; set; }
        public Nullable<int> userInsertCode { get; set; }
        public Nullable<System.DateTime> dateInsert { get; set; }
        public string ipInsert { get; set; }
        public Nullable<int> userUpdateCode { get; set; }
        public Nullable<System.DateTime> dateUpdate { get; set; }
        public string ipUpdate { get; set; }
    
        public virtual card card { get; set; }
        public virtual skillDegree skillDegree { get; set; }
        public virtual statusFirstAttendMonthWSDL statusFirstAttendMonthWSDL { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual worker worker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workerAttendanceInsurance> workerAttendanceInsurances { get; set; }
        public virtual process process { get; set; }
    }
}
