//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class workerDetail
    {
        public int workerDetailsCode { get; set; }
        public int workerCode { get; set; }
        public Nullable<int> careerCode { get; set; }
        public Nullable<int> govermentCode { get; set; }
        public Nullable<int> centerCode { get; set; }
        public Nullable<int> villageCode { get; set; }
        public Nullable<int> skillDegreeCode { get; set; }
        public Nullable<System.DateTime> dateSkillDegree { get; set; }
        public Nullable<bool> currentStatusSkill { get; set; }
        public Nullable<int> medicalInsuranceCode { get; set; }
        public Nullable<System.DateTime> dateMedicalInsurance { get; set; }
        public Nullable<bool> currentStatusMedical { get; set; }
        public Nullable<int> cardCode { get; set; }
        public Nullable<int> userInsertCode { get; set; }
        public Nullable<System.DateTime> dateInsert { get; set; }
        public string ipInsert { get; set; }
        public Nullable<int> userUpdateCode { get; set; }
        public Nullable<System.DateTime> dateUpdate { get; set; }
        public string ipUpdate { get; set; }
    
        public virtual card card { get; set; }
        public virtual career career { get; set; }
        public virtual medicalStatu medicalStatu { get; set; }
        public virtual skillDegree skillDegree { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual worker worker { get; set; }
    }
}
