//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class workerAttendanceInsurance
    {
        public int workerAttendanceInsuranceCode { get; set; }
        public int workerAttendanceCode { get; set; }
        public Nullable<int> insuranceStatus { get; set; }
        public string insuranceStatusDescription { get; set; }
    
        public virtual workerAttendance workerAttendance { get; set; }
    }
}
