//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiWSDLs.coverWsdl {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="file://target.files", ConfigurationName="coverWsdl.CNTCOVPortType")]
    public interface CNTCOVPortType {
        
        // CODEGEN: Generating message contract since the operation CNTCOVOperation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:CNTCOV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        apiWSDLs.coverWsdl.CNTCOVOperationResponse CNTCOVOperation(apiWSDLs.coverWsdl.CNTCOVOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:CNTCOV", ReplyAction="*")]
        System.Threading.Tasks.Task<apiWSDLs.coverWsdl.CNTCOVOperationResponse> CNTCOVOperationAsync(apiWSDLs.coverWsdl.CNTCOVOperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.CNTCOVI.com/schemas/CNTCOVIInterface")]
    public partial class DFHCOMMAREA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private dfhcommarea_buffer bufferField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public dfhcommarea_buffer buffer {
            get {
                return this.bufferField;
            }
            set {
                this.bufferField = value;
                this.RaisePropertyChanged("buffer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.CNTCOVI.com/schemas/CNTCOVIInterface")]
    public partial class dfhcommarea_buffer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int payer_numberField;
        
        private int date1Field;
        
        private short zone1Field;
        
        private short ofic1Field;
        
        private short mahara1Field;
        
        private long cnt_numField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int payer_number {
            get {
                return this.payer_numberField;
            }
            set {
                this.payer_numberField = value;
                this.RaisePropertyChanged("payer_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int date1 {
            get {
                return this.date1Field;
            }
            set {
                this.date1Field = value;
                this.RaisePropertyChanged("date1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public short zone1 {
            get {
                return this.zone1Field;
            }
            set {
                this.zone1Field = value;
                this.RaisePropertyChanged("zone1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public short ofic1 {
            get {
                return this.ofic1Field;
            }
            set {
                this.ofic1Field = value;
                this.RaisePropertyChanged("ofic1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public short mahara1 {
            get {
                return this.mahara1Field;
            }
            set {
                this.mahara1Field = value;
                this.RaisePropertyChanged("mahara1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long cnt_num {
            get {
                return this.cnt_numField;
            }
            set {
                this.cnt_numField = value;
                this.RaisePropertyChanged("cnt_num");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="dfhcommarea_buffer", Namespace="http://www.CNTCOVO.com/schemas/CNTCOVOInterface")]
    public partial class dfhcommarea_buffer1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int payer_numberField;
        
        private int date1Field;
        
        private short zone1Field;
        
        private short ofic1Field;
        
        private short mahara1Field;
        
        private long cnt_numField;
        
        private string processing_statusdesccField;
        
        private string processing_statusdescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int payer_number {
            get {
                return this.payer_numberField;
            }
            set {
                this.payer_numberField = value;
                this.RaisePropertyChanged("payer_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int date1 {
            get {
                return this.date1Field;
            }
            set {
                this.date1Field = value;
                this.RaisePropertyChanged("date1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public short zone1 {
            get {
                return this.zone1Field;
            }
            set {
                this.zone1Field = value;
                this.RaisePropertyChanged("zone1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public short ofic1 {
            get {
                return this.ofic1Field;
            }
            set {
                this.ofic1Field = value;
                this.RaisePropertyChanged("ofic1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public short mahara1 {
            get {
                return this.mahara1Field;
            }
            set {
                this.mahara1Field = value;
                this.RaisePropertyChanged("mahara1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long cnt_num {
            get {
                return this.cnt_numField;
            }
            set {
                this.cnt_numField = value;
                this.RaisePropertyChanged("cnt_num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string processing_statusdescc {
            get {
                return this.processing_statusdesccField;
            }
            set {
                this.processing_statusdesccField = value;
                this.RaisePropertyChanged("processing_statusdescc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string processing_statusdesc {
            get {
                return this.processing_statusdescField;
            }
            set {
                this.processing_statusdescField = value;
                this.RaisePropertyChanged("processing_statusdesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="DFHCOMMAREA", Namespace="http://www.CNTCOVO.com/schemas/CNTCOVOInterface")]
    public partial class DFHCOMMAREA1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private dfhcommarea_buffer1 bufferField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public dfhcommarea_buffer1 buffer {
            get {
                return this.bufferField;
            }
            set {
                this.bufferField = value;
                this.RaisePropertyChanged("buffer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CNTCOVOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.CNTCOVI.com/schemas/CNTCOVIInterface", Order=0)]
        public apiWSDLs.coverWsdl.DFHCOMMAREA DFHCOMMAREA;
        
        public CNTCOVOperationRequest() {
        }
        
        public CNTCOVOperationRequest(apiWSDLs.coverWsdl.DFHCOMMAREA DFHCOMMAREA) {
            this.DFHCOMMAREA = DFHCOMMAREA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CNTCOVOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.CNTCOVO.com/schemas/CNTCOVOInterface", Order=0)]
        public apiWSDLs.coverWsdl.DFHCOMMAREA1 DFHCOMMAREA;
        
        public CNTCOVOperationResponse() {
        }
        
        public CNTCOVOperationResponse(apiWSDLs.coverWsdl.DFHCOMMAREA1 DFHCOMMAREA) {
            this.DFHCOMMAREA = DFHCOMMAREA;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CNTCOVPortTypeChannel : apiWSDLs.coverWsdl.CNTCOVPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CNTCOVPortTypeClient : System.ServiceModel.ClientBase<apiWSDLs.coverWsdl.CNTCOVPortType>, apiWSDLs.coverWsdl.CNTCOVPortType {
        
        public CNTCOVPortTypeClient() {
        }
        
        public CNTCOVPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CNTCOVPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CNTCOVPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CNTCOVPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        apiWSDLs.coverWsdl.CNTCOVOperationResponse apiWSDLs.coverWsdl.CNTCOVPortType.CNTCOVOperation(apiWSDLs.coverWsdl.CNTCOVOperationRequest request) {
            return base.Channel.CNTCOVOperation(request);
        }
        
        public apiWSDLs.coverWsdl.DFHCOMMAREA1 CNTCOVOperation(apiWSDLs.coverWsdl.DFHCOMMAREA DFHCOMMAREA) {
            apiWSDLs.coverWsdl.CNTCOVOperationRequest inValue = new apiWSDLs.coverWsdl.CNTCOVOperationRequest();
            inValue.DFHCOMMAREA = DFHCOMMAREA;
            apiWSDLs.coverWsdl.CNTCOVOperationResponse retVal = ((apiWSDLs.coverWsdl.CNTCOVPortType)(this)).CNTCOVOperation(inValue);
            return retVal.DFHCOMMAREA;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<apiWSDLs.coverWsdl.CNTCOVOperationResponse> apiWSDLs.coverWsdl.CNTCOVPortType.CNTCOVOperationAsync(apiWSDLs.coverWsdl.CNTCOVOperationRequest request) {
            return base.Channel.CNTCOVOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<apiWSDLs.coverWsdl.CNTCOVOperationResponse> CNTCOVOperationAsync(apiWSDLs.coverWsdl.DFHCOMMAREA DFHCOMMAREA) {
            apiWSDLs.coverWsdl.CNTCOVOperationRequest inValue = new apiWSDLs.coverWsdl.CNTCOVOperationRequest();
            inValue.DFHCOMMAREA = DFHCOMMAREA;
            return ((apiWSDLs.coverWsdl.CNTCOVPortType)(this)).CNTCOVOperationAsync(inValue);
        }
    }
}
