//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiWSDLs.srvRefContRefSidesData {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="file://target.files", ConfigurationName="srvRefContRefSidesData.CNTV04PortType")]
    public interface CNTV04PortType {
        
        // CODEGEN: Generating message contract since the operation CNTV04Operation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:CNTV04", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        apiWSDLs.srvRefContRefSidesData.CNTV04OperationResponse CNTV04Operation(apiWSDLs.srvRefContRefSidesData.CNTV04OperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:CNTV04", ReplyAction="*")]
        System.Threading.Tasks.Task<apiWSDLs.srvRefContRefSidesData.CNTV04OperationResponse> CNTV04OperationAsync(apiWSDLs.srvRefContRefSidesData.CNTV04OperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.CNTV04I.com/schemas/CNTV04IInterface")]
    public partial class COMMAREA02 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string arc_gpsbin_commField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string arc_gpsbin_comm {
            get {
                return this.arc_gpsbin_commField;
            }
            set {
                this.arc_gpsbin_commField = value;
                this.RaisePropertyChanged("arc_gpsbin_comm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.CNTV04O.com/schemas/CNTV04OInterface")]
    public partial class Commarea_buffer__01 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string comm_area_01Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string comm_area_01 {
            get {
                return this.comm_area_01Field;
            }
            set {
                this.comm_area_01Field = value;
                this.RaisePropertyChanged("comm_area_01");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CNTV04OperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.CNTV04I.com/schemas/CNTV04IInterface", Order=0)]
        public apiWSDLs.srvRefContRefSidesData.COMMAREA02 COMMAREA02;
        
        public CNTV04OperationRequest() {
        }
        
        public CNTV04OperationRequest(apiWSDLs.srvRefContRefSidesData.COMMAREA02 COMMAREA02) {
            this.COMMAREA02 = COMMAREA02;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CNTV04OperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.CNTV04O.com/schemas/CNTV04OInterface", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("buffer_01", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public apiWSDLs.srvRefContRefSidesData.Commarea_buffer__01[] COMMAREA;
        
        public CNTV04OperationResponse() {
        }
        
        public CNTV04OperationResponse(apiWSDLs.srvRefContRefSidesData.Commarea_buffer__01[] COMMAREA) {
            this.COMMAREA = COMMAREA;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CNTV04PortTypeChannel : apiWSDLs.srvRefContRefSidesData.CNTV04PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CNTV04PortTypeClient : System.ServiceModel.ClientBase<apiWSDLs.srvRefContRefSidesData.CNTV04PortType>, apiWSDLs.srvRefContRefSidesData.CNTV04PortType {
        
        public CNTV04PortTypeClient() {
        }
        
        public CNTV04PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CNTV04PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CNTV04PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CNTV04PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        apiWSDLs.srvRefContRefSidesData.CNTV04OperationResponse apiWSDLs.srvRefContRefSidesData.CNTV04PortType.CNTV04Operation(apiWSDLs.srvRefContRefSidesData.CNTV04OperationRequest request) {
            return base.Channel.CNTV04Operation(request);
        }
        
        public apiWSDLs.srvRefContRefSidesData.Commarea_buffer__01[] CNTV04Operation(apiWSDLs.srvRefContRefSidesData.COMMAREA02 COMMAREA02) {
            apiWSDLs.srvRefContRefSidesData.CNTV04OperationRequest inValue = new apiWSDLs.srvRefContRefSidesData.CNTV04OperationRequest();
            inValue.COMMAREA02 = COMMAREA02;
            apiWSDLs.srvRefContRefSidesData.CNTV04OperationResponse retVal = ((apiWSDLs.srvRefContRefSidesData.CNTV04PortType)(this)).CNTV04Operation(inValue);
            return retVal.COMMAREA;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<apiWSDLs.srvRefContRefSidesData.CNTV04OperationResponse> apiWSDLs.srvRefContRefSidesData.CNTV04PortType.CNTV04OperationAsync(apiWSDLs.srvRefContRefSidesData.CNTV04OperationRequest request) {
            return base.Channel.CNTV04OperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<apiWSDLs.srvRefContRefSidesData.CNTV04OperationResponse> CNTV04OperationAsync(apiWSDLs.srvRefContRefSidesData.COMMAREA02 COMMAREA02) {
            apiWSDLs.srvRefContRefSidesData.CNTV04OperationRequest inValue = new apiWSDLs.srvRefContRefSidesData.CNTV04OperationRequest();
            inValue.COMMAREA02 = COMMAREA02;
            return ((apiWSDLs.srvRefContRefSidesData.CNTV04PortType)(this)).CNTV04OperationAsync(inValue);
        }
    }
}
