//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiWSDLs.srvRefNationalData {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="file://target.files", ConfigurationName="srvRefNationalData.CNTV02PortType")]
    public interface CNTV02PortType {
        
        // CODEGEN: Generating message contract since the operation CNTV02Operation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:CNTV02", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        apiWSDLs.srvRefNationalData.CNTV02OperationResponse CNTV02Operation(apiWSDLs.srvRefNationalData.CNTV02OperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:CNTV02", ReplyAction="*")]
        System.Threading.Tasks.Task<apiWSDLs.srvRefNationalData.CNTV02OperationResponse> CNTV02OperationAsync(apiWSDLs.srvRefNationalData.CNTV02OperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.CNTV02I.com/schemas/CNTV02IInterface")]
    public partial class COMMAREA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private commarea_buffer__01 buffer_01Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public commarea_buffer__01 buffer_01 {
            get {
                return this.buffer_01Field;
            }
            set {
                this.buffer_01Field = value;
                this.RaisePropertyChanged("buffer_01");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.CNTV02I.com/schemas/CNTV02IInterface")]
    public partial class commarea_buffer__01 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string comm_area_01Field;
        
        private string comm_area_011Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string comm_area_01 {
            get {
                return this.comm_area_01Field;
            }
            set {
                this.comm_area_01Field = value;
                this.RaisePropertyChanged("comm_area_01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string comm_area_011 {
            get {
                return this.comm_area_011Field;
            }
            set {
                this.comm_area_011Field = value;
                this.RaisePropertyChanged("comm_area_011");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.CNTV02O.com/schemas/CNTV02OInterface")]
    public partial class COMMAREA2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ws_arc_insnum_commField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ws_arc_insnum_comm {
            get {
                return this.ws_arc_insnum_commField;
            }
            set {
                this.ws_arc_insnum_commField = value;
                this.RaisePropertyChanged("ws_arc_insnum_comm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CNTV02OperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.CNTV02I.com/schemas/CNTV02IInterface", Order=0)]
        public apiWSDLs.srvRefNationalData.COMMAREA COMMAREA;
        
        public CNTV02OperationRequest() {
        }
        
        public CNTV02OperationRequest(apiWSDLs.srvRefNationalData.COMMAREA COMMAREA) {
            this.COMMAREA = COMMAREA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CNTV02OperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.CNTV02O.com/schemas/CNTV02OInterface", Order=0)]
        public apiWSDLs.srvRefNationalData.COMMAREA2 COMMAREA2;
        
        public CNTV02OperationResponse() {
        }
        
        public CNTV02OperationResponse(apiWSDLs.srvRefNationalData.COMMAREA2 COMMAREA2) {
            this.COMMAREA2 = COMMAREA2;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CNTV02PortTypeChannel : apiWSDLs.srvRefNationalData.CNTV02PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CNTV02PortTypeClient : System.ServiceModel.ClientBase<apiWSDLs.srvRefNationalData.CNTV02PortType>, apiWSDLs.srvRefNationalData.CNTV02PortType {
        
        public CNTV02PortTypeClient() {
        }
        
        public CNTV02PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CNTV02PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CNTV02PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CNTV02PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        apiWSDLs.srvRefNationalData.CNTV02OperationResponse apiWSDLs.srvRefNationalData.CNTV02PortType.CNTV02Operation(apiWSDLs.srvRefNationalData.CNTV02OperationRequest request) {
            return base.Channel.CNTV02Operation(request);
        }
        
        public apiWSDLs.srvRefNationalData.COMMAREA2 CNTV02Operation(apiWSDLs.srvRefNationalData.COMMAREA COMMAREA) {
            apiWSDLs.srvRefNationalData.CNTV02OperationRequest inValue = new apiWSDLs.srvRefNationalData.CNTV02OperationRequest();
            inValue.COMMAREA = COMMAREA;
            apiWSDLs.srvRefNationalData.CNTV02OperationResponse retVal = ((apiWSDLs.srvRefNationalData.CNTV02PortType)(this)).CNTV02Operation(inValue);
            return retVal.COMMAREA2;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<apiWSDLs.srvRefNationalData.CNTV02OperationResponse> apiWSDLs.srvRefNationalData.CNTV02PortType.CNTV02OperationAsync(apiWSDLs.srvRefNationalData.CNTV02OperationRequest request) {
            return base.Channel.CNTV02OperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<apiWSDLs.srvRefNationalData.CNTV02OperationResponse> CNTV02OperationAsync(apiWSDLs.srvRefNationalData.COMMAREA COMMAREA) {
            apiWSDLs.srvRefNationalData.CNTV02OperationRequest inValue = new apiWSDLs.srvRefNationalData.CNTV02OperationRequest();
            inValue.COMMAREA = COMMAREA;
            return ((apiWSDLs.srvRefNationalData.CNTV02PortType)(this)).CNTV02OperationAsync(inValue);
        }
    }
}
