//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vt_nationalAuthority {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class generalVariables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal generalVariables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vt_nationalAuthority.generalVariables", typeof(generalVariables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم رفع مرفقات حتى الان.
        /// </summary>
        public static string AttachmentsNotFound {
            get {
                return ResourceManager.GetString("AttachmentsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تسجيل نوع مرفق حتى الان.
        /// </summary>
        public static string AttachmentTypeNotFound {
            get {
                return ResourceManager.GetString("AttachmentTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوا , لم يتم ارسال الحضور للتأمينات &apos;,2);&lt;/script&gt;.
        /// </summary>
        public static string AttendInsuranceNotSent {
            get {
                return ResourceManager.GetString("AttendInsuranceNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;تم استرجاع العمليه لطلبات العمليات بنجاح.&apos;,0);&lt;/script&gt;.
        /// </summary>
        public static string BackProcessDone {
            get {
                return ResourceManager.GetString("BackProcessDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوا , الرجاء المحاوله مره اخرى &apos;,2);&lt;/script&gt;.
        /// </summary>
        public static string BackProcessNotDone {
            get {
                return ResourceManager.GetString("BackProcessNotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا هذا العامل ليس لديه كارت ليتم تفعيله او ايقافه.
        /// </summary>
        public static string CardRequestDeActivation {
            get {
                return ResourceManager.GetString("CardRequestDeActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوا , يجب ادخال عمال اولا&apos;,1);&lt;/script&gt;.
        /// </summary>
        public static string CardRequestError {
            get {
                return ResourceManager.GetString("CardRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تسجيل طلبات كروت بعد.
        /// </summary>
        public static string CardsRequestNotFound {
            get {
                return ResourceManager.GetString("CardsRequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;الرجاء تغيير اسم المرفق او نوع المرفق&apos;,2);&lt;/script&gt;.
        /// </summary>
        public static string changeFilderName {
            get {
                return ResourceManager.GetString("changeFilderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تسجيل مهام حتى الان.
        /// </summary>
        public static string ContractorsMissionNotFound {
            get {
                return ResourceManager.GetString("ContractorsMissionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تسجيل مقاولين حتى الان.
        /// </summary>
        public static string ContractorsNotFound {
            get {
                return ResourceManager.GetString("ContractorsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;تم الحذف بنجاح&apos;,0);&lt;/script&gt;.
        /// </summary>
        public static string DeleteDone {
            get {
                return ResourceManager.GetString("DeleteDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوا , لم يتم الحذف لارتباطه بعناصر اخرى&apos;,1);&lt;/script&gt;.
        /// </summary>
        public static string DeleteNotDone {
            get {
                return ResourceManager.GetString("DeleteNotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;تم التعديل بنجاح&apos;,0);&lt;/script&gt;.
        /// </summary>
        public static string EditDone {
            get {
                return ResourceManager.GetString("EditDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوا , هذا العنصر موجود سابقاً&apos;,1);&lt;/script&gt;.
        /// </summary>
        public static string EditNotDone {
            get {
                return ResourceManager.GetString("EditNotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;تم التأكيد على المستخلص بنجاح.&apos;,0);&lt;/script&gt;.
        /// </summary>
        public static string ExtractAccept {
            get {
                return ResourceManager.GetString("ExtractAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوا , لم يتم التأكيد على المستخلص &apos;,1);&lt;/script&gt;.
        /// </summary>
        public static string ExtractNotAccept {
            get {
                return ResourceManager.GetString("ExtractNotAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوأ , لم يتم التأكيد على الاشتراك .&apos;,1);&lt;/script&gt;.
        /// </summary>
        public static string ExtractNotPaid {
            get {
                return ResourceManager.GetString("ExtractNotPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;تم التأكيد على الاشتراك بنجاح.&apos;,0);&lt;/script&gt;.
        /// </summary>
        public static string ExtractPaid {
            get {
                return ResourceManager.GetString("ExtractPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تسجيل مستخلصات حتى الان.
        /// </summary>
        public static string ExtractsNotFound {
            get {
                return ResourceManager.GetString("ExtractsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تسجيل مجموعات حتى الان.
        /// </summary>
        public static string GroupNotFound {
            get {
                return ResourceManager.GetString("GroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوا , يوجد خطأ في الرقم القومى&apos;,1);&lt;/script&gt;.
        /// </summary>
        public static string NationalID {
            get {
                return ResourceManager.GetString("NationalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوا ,لا يمكنك ادخال / تعديل البيانات&apos;, 1);&lt;/script&gt;.
        /// </summary>
        public static string NotAllowOperation {
            get {
                return ResourceManager.GetString("NotAllowOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تسجيل ملاحظات حتى الان.
        /// </summary>
        public static string NotesNotFound {
            get {
                return ResourceManager.GetString("NotesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد اشعارات جديده.
        /// </summary>
        public static string NotificationNotFound {
            get {
                return ResourceManager.GetString("NotificationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;تم تغيير كلمه المرور بنجاح &apos;,0);&lt;/script&gt;.
        /// </summary>
        public static string passwordChangeDone {
            get {
                return ResourceManager.GetString("passwordChangeDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوا, لما يتم تغيير كلمه المرور , الرجاء المحاوله مره اخرى &apos;,2);&lt;/script&gt;.
        /// </summary>
        public static string passwordChangeNotDone {
            get {
                return ResourceManager.GetString("passwordChangeNotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;الرجاء جعل الكلمه المرور الجديده تطابق تأكيد كلمه المرور الجديده &apos;,2);&lt;/script&gt;.
        /// </summary>
        public static string passwordNotEqual {
            get {
                return ResourceManager.GetString("passwordNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوا , كلمه المرور الحاليه خاطئه , الرجاء كتابه كلمه المرور الصحيحه&apos;,1);&lt;/script&gt;.
        /// </summary>
        public static string passwordWrong {
            get {
                return ResourceManager.GetString("passwordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوا , ليس لديك الصلاحية.&apos;, 1);&lt;/script&gt;.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;تم الموافقة على الطلب بنجاح.&apos;,0);&lt;/script&gt;.
        /// </summary>
        public static string ProcessAccept {
            get {
                return ResourceManager.GetString("ProcessAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم استبعاد العمليه.
        /// </summary>
        public static string processCancel {
            get {
                return ResourceManager.GetString("processCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم استبعاد العمليه.
        /// </summary>
        public static string processCancelNot {
            get {
                return ResourceManager.GetString("processCancelNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوا , لم يتم الموافقة على الطلب&apos;,1);&lt;/script&gt;.
        /// </summary>
        public static string ProcessNotAccept {
            get {
                return ResourceManager.GetString("ProcessNotAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد عمليات.
        /// </summary>
        public static string ProcessNotFound {
            get {
                return ResourceManager.GetString("ProcessNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تسجيل ايقاف لهذه العمليه حتى الان.
        /// </summary>
        public static string ProcessStopNotFound {
            get {
                return ResourceManager.GetString("ProcessStopNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد جهات اسناد - مقاولين.
        /// </summary>
        public static string RefSideContNotFound {
            get {
                return ResourceManager.GetString("RefSideContNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;تم الحفظ بنجاح&apos;,0);&lt;/script&gt;.
        /// </summary>
        public static string SaveDone {
            get {
                return ResourceManager.GetString("SaveDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوا , هذا العنصر موجود سابقاً&apos;,1);&lt;/script&gt;.
        /// </summary>
        public static string SaveNotDone {
            get {
                return ResourceManager.GetString("SaveNotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوا , تم الحفظ بنجاح ولكن امتداد الصوره لابد ان يكون من نوع  jpg,jpeg,png,tiff&apos;,2);&lt;/script&gt;.
        /// </summary>
        public static string SaveWithoutImage {
            get {
                return ResourceManager.GetString("SaveWithoutImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;تم إلغاء البحث بنجاح.&apos;,0);&lt;/script&gt;.
        /// </summary>
        public static string SearchCancel {
            get {
                return ResourceManager.GetString("SearchCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد نتائج.
        /// </summary>
        public static string SearchNotFound {
            get {
                return ResourceManager.GetString("SearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;تم قبول هذا المقاول بنجاح &apos;,0);&lt;/script&gt;.
        /// </summary>
        public static string SubContractorAccept {
            get {
                return ResourceManager.GetString("SubContractorAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوا , لم يتم قبول هذا المقاول الرجاء المحاوله مره اخرى &apos;,2);&lt;/script&gt;.
        /// </summary>
        public static string SubContractorNotAccept {
            get {
                return ResourceManager.GetString("SubContractorNotAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;يوجد خطأ فى اسم المستخدم او كلمة السر&apos;,1);&lt;/script&gt;.
        /// </summary>
        public static string UserLoginFailed {
            get {
                return ResourceManager.GetString("UserLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوا , المستخدم ليس لديه صلاحيه&apos;,1);&lt;/script&gt;.
        /// </summary>
        public static string UserNotAcess {
            get {
                return ResourceManager.GetString("UserNotAcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوا..هذا الحساب غير فعال&apos;,1);&lt;/script&gt;.
        /// </summary>
        public static string UserNotActive {
            get {
                return ResourceManager.GetString("UserNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوا , يجب اختيار المقاول اولا&apos;,1);&lt;/script&gt;.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;sAlert(&apos;عفوا , هناك عمال مسجلين بهذه الفتره &apos;,2);&lt;/script&gt;.
        /// </summary>
        public static string WorkerAttendanceFound {
            get {
                return ResourceManager.GetString("WorkerAttendanceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا العامل ليس لديه كروت.
        /// </summary>
        public static string WorkerCardsNotFound {
            get {
                return ResourceManager.GetString("WorkerCardsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تسجيل حالة  ايقاف / تفعيل كارت حتى الان.
        /// </summary>
        public static string WorkerCardsNotSave {
            get {
                return ResourceManager.GetString("WorkerCardsNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تسجيل اصابات بعد.
        /// </summary>
        public static string WorkerInjuries {
            get {
                return ResourceManager.GetString("WorkerInjuries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تحضير هذا العامل حتى الان.
        /// </summary>
        public static string WorkerProcessNotFound {
            get {
                return ResourceManager.GetString("WorkerProcessNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تسجيل عمال حتى الان.
        /// </summary>
        public static string WorkersNotfound {
            get {
                return ResourceManager.GetString("WorkersNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تسجيل هاتف حتى الان.
        /// </summary>
        public static string WorkersPhoneNotFound {
            get {
                return ResourceManager.GetString("WorkersPhoneNotFound", resourceCulture);
            }
        }
    }
}
